config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index', :as => 'home'
  get 'welcome/photos', :as => 'photo'
  get 'welcome/products', :as => 'product'
  get 'welcome/contact_us', :as => 'contact_us'

  root 'welcome#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_header.htm.erb
<div class="top-bar">
		<div class="top-bar-left">
			<ul class="menu">
				<li class="menu-text"><%= link_to "Miss Carol's Ballet Boutique" home_path %></li>
				<li><%= link_to "Contact Us", contact_us_path %></li>
				<li><%= link_to "Products", product_path %></li>
				<li><%= link_to "Photos", photo_path %></a></li>
			</ul>
		</div>
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet" href="http://dhbhdrzi4tiry.cloudfront.net/cdn/sites/foundation.min.css">
    

    <title><%= content_for?(:title) ? yield(:title) : "Miss Carol's Ballet Boutique" %></title>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application" 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>

app/views/welcome/contact_us.html.erb
contact_us.html.erb

app/views/welcome/index.html.erb
<!-- <h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p> -->
<!doctype html>
	<html class="no-js" lang="en">
	<body>
		<div class="top-bar">
			<div class="row">
				<div class="top-bar-left">
					<ul class="dropdown menu" data-dropdown-menu>
						<li class="menu-text"><%= link_to "Miss Carol's Ballet Boutique", home_path %></li>
						<li><%= link_to "Contact Us", contact_us_path %></li>
						<li><%= link_to "Products", product_path %></li>
						<li><%= link_to "Photos", photo_path %></a></li>
					</ul>
				</div>
				<div class="top-bar-right"></div>
			</div>
		</div> 
		<br>
		<div class="row">
			<div class="medium-6 columns">
				<%= image_tag "bunny-band.jpg", class: 'thumbnail' %>
					<div class="row small-up-4">
						<div class="column">
							<%= image_tag "rose-band.jpg", class: 'thumbnail' %>
						</div>
						<div class="column">
							<%= image_tag "rose-band.jpg", class: 'thumbnail' %>
						</div>
						<div class="column">
							<%= image_tag "rose-band.jpg", class: 'thumbnail' %>
						</div>
						<div class="column">
							<%= image_tag "rose-band.jpg", class: 'thumbnail' %>
						</div>
					</div>
				</div>
			<div class="medium-6 large-5 columns">
				<h3>About My Boutique</h3>
				<p>I am very excited to introduce my business, <i>Miss Carol’s Ballet Boutique</i>. For many years, I have been using my talent to create headpieces for my ballet and tap dance classes’ recital costumes. This talent has lead me to create hair pieces that can be enjoyed year round, in and out of dance classes. Similar designs inspired me to create unique dance bags and everyday totes. Please enjoy browsing my online boutique and if you see something you like, please contact me so I can provide you with your very own Miss Carol’s Ballet Boutique masterpiece. Remember, each item is hand crafted and final products will vary. Custom orders are available based on time and materials. Please use the email contact link when you are ready to order your very own Miss Carol’s Ballet Boutique creation!</p>
			</div>			
		</div>
		<script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
		<script src="http://dhbhdrzi4tiry.cloudfront.net/cdn/sites/foundation.js"></script>
		<script>
	      $(document).foundation();
	    </script>
	</body>
</html>

app/views/welcome/photos.html.erb
<div class="row column">
	<h3>Product Gallery</h3>
</div>
<hr>
<div class="row column">
	<h4>Special Orders</h4>
</div>
<div class="row medium-up-3 large-up-4">
	<div class="column">
		<%= image_tag "special_flower-band.jpg", class: 'thumbnail' %>
	</div>
	<div class="column">
		<%= image_tag "special_flower-band.jpg", class: 'thumbnail' %>
	</div>
	<div class="column">
		<%= image_tag "special_flower-band.jpg", class: 'thumbnail' %>
	</div>
	<div class="column">
		<%= image_tag "special_flower-band.jpg", class: 'thumbnail' %>
	</div>
</div>
<hr>
<div class="row column">
	<h4>Butterfly Collection</h4>
</div>
<div class="row medium-up-3 large-up-4">
	<div class="column">
		<%= image_tag "special_flower-band.jpg", class: 'thumbnail' %>
	</div>
	<div class="column">
		<%= image_tag "special_flower-band.jpg", class: 'thumbnail' %>
	</div>
	<div class="column">
		<%= image_tag "special_flower-band.jpg", class: 'thumbnail' %>
	</div>
	<div class="column">
		<%= image_tag "special_flower-band.jpg", class: 'thumbnail' %>
	</div>
</div>
<hr>
<div class="row column">
	<h4>Flower Collection</h4>
</div>
<div class="row medium-up-3 large-up-4">
	<div class="column">
		<%= image_tag "special_flower-band.jpg", class: 'thumbnail' %>
	</div>
	<div class="column">
		<%= image_tag "special_flower-band.jpg", class: 'thumbnail' %>
	</div>
	<div class="column">
		<%= image_tag "special_flower-band.jpg", class: 'thumbnail' %>
	</div>
	<div class="column">
		<%= image_tag "special_flower-band.jpg", class: 'thumbnail' %>
	</div>
</div>
<hr>
<div class="row column">
	<h4>Easter Collection</h4>
</div>
<div class="row medium-up-3 large-up-4">
	<div class="column">
		<%= image_tag "special_flower-band.jpg", class: 'thumbnail' %>
	</div>
	<div class="column">
		<%= image_tag "special_flower-band.jpg", class: 'thumbnail' %>
	</div>
	<div class="column">
		<%= image_tag "special_flower-band.jpg", class: 'thumbnail' %>
	</div>
	<div class="column">
		<%= image_tag "special_flower-band.jpg", class: 'thumbnail' %>
	</div>
</div>
<hr>
<div class="row column">
	<h4>Barrettes</h4>
</div>
<div class="row medium-up-3 large-up-4">
	<div class="column">
		<%= image_tag "special_flower-band.jpg", class: 'thumbnail' %>
	</div>
	<div class="column">
		<%= image_tag "special_flower-band.jpg", class: 'thumbnail' %>
	</div>
	<div class="column">
		<%= image_tag "special_flower-band.jpg", class: 'thumbnail' %>
	</div>
	<div class="column">
		<%= image_tag "special_flower-band.jpg", class: 'thumbnail' %>
	</div>
</div>
<hr>
<div class="row column">
	<h4>Fall Collection</h4>
</div>
<div class="row medium-up-3 large-up-4">
	<div class="column">
		<%= image_tag "special_flower-band.jpg", class: 'thumbnail' %>
	</div>
	<div class="column">
		<%= image_tag "special_flower-band.jpg", class: 'thumbnail' %>
	</div>
	<div class="column">
		<%= image_tag "special_flower-band.jpg", class: 'thumbnail' %>
	</div>
	<div class="column">
		<%= image_tag "special_flower-band.jpg", class: 'thumbnail' %>
	</div>
	<div class="column">
		<%= image_tag "special_flower-band.jpg", class: 'thumbnail' %>
	</div>
	<div class="column">
		<%= image_tag "special_flower-band.jpg", class: 'thumbnail' %>
	</div>
	<div class="column">
		<%= image_tag "special_flower-band.jpg", class: 'thumbnail' %>
	</div>
	<div class="column">
		<%= image_tag "special_flower-band.jpg", class: 'thumbnail' %>
	</div>
</div>
<hr>
<div class="row column">
	<h4>Winter Collection</h4>
</div>
<div class="row medium-up-3 large-up-4">
	<div class="column">
		<%= image_tag "special_flower-band.jpg", class: 'thumbnail' %>
	</div>
	<div class="column">
		<%= image_tag "special_flower-band.jpg", class: 'thumbnail' %>
	</div>
	<div class="column">
		<%= image_tag "special_flower-band.jpg", class: 'thumbnail' %>
	</div>
	<div class="column">
		<%= image_tag "special_flower-band.jpg", class: 'thumbnail' %>
	</div>
	<div class="column">
		<%= image_tag "special_flower-band.jpg", class: 'thumbnail' %>
	</div>
	<div class="column">
		<%= image_tag "special_flower-band.jpg", class: 'thumbnail' %>
	</div>
	<div class="column">
		<%= image_tag "special_flower-band.jpg", class: 'thumbnail' %>
	</div>
	<div class="column">
		<%= image_tag "special_flower-band.jpg", class: 'thumbnail' %>
	</div>
</div>
<hr>
<div class="row column">
	<h4>Ballet Bags</h4>
</div>
<div class="row medium-up-3 large-up-4">
	<div class="column">
		<%= image_tag "special_flower-band.jpg", class: 'thumbnail' %>
	</div>
	<div class="column">
		<%= image_tag "special_flower-band.jpg", class: 'thumbnail' %>
	</div>
	<div class="column">
		<%= image_tag "special_flower-band.jpg", class: 'thumbnail' %>
	</div>
	<div class="column">
		<%= image_tag "special_flower-band.jpg", class: 'thumbnail' %>
	</div>
</div>

app/views/welcome/products.html.erb
products.html.erb